

service: aws-python3 # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: python3.6
  region: ap-southeast-2
  profile: leases16

# you can overwrite defaults here
#  stage: dev

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "cloudwatch:PutMetricData"
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
        - "ec2:CreateNetworkInterface"
        - "ec2:DescribeNetworkInterfaces"
        - "ec2:DeleteNetworkInterface"
      Resource: '*'

# you can add packaging information here
#package:
#  include:
#    - include-me.py
#    - include-me-dir/**
#  exclude:
#    - exclude-me.py
#    - exclude-me-dir/**

functions:
  portcheck:
    handler: handler.port_check
    vpc:
      securityGroupIds:
        - sg-0eaa7067c2b3a965e
      subnetIds:
        - subnet-07d76a72903ff992d
        - subnet-0958b39c31c3d3524
        - subnet-004d66c5d9e49a6aa

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
